### ISSUE TITLE
make perl6- prefix optional

### ISSUE THREAD

**Issue by melezhik** [gfldex/perl6-meta6-bin#1]
Hi!

When create directory to hold project data, can we make "perl6-" prefix optional? Or maybe even create directory without it. What do you think?

**Comment by gfldex** [comment]
I spend quite some time thinking about that matter. My observation is that quite a few ppl use some sort of prefix for projects `perl6-` and `p6-` are common judgeing by the ecosystem. It allows for having Perl5 and Perl 6 projects in the same directory without causing confusion. Github got their topic system now but it doesn't translate to URLs. So from the standpoint of a casual user it's easiert to spot what this is about. And it's not just the directory name because the github repo name is derived from it too. There may be good reason to implement the same module for Ruby and Perl 6 (I know, wishful thinking :).

I settled for the longer form mostly for URL/github repo name clarity. And if you autocomplete in a shell it doesn't make any difference.

So no I don't like provide even the option to remove the prefix. If you really don't linke it you can always rename the directory with a shellscript wrapper or just use a local fork so tweak it (maybe not the best option right now but it wont change all that much in the future).

If you have good arguments for why the prefix is a bad idea please share.

**Comment by melezhik** [comment]
Hi, more or less I just wanted to hear your arguments for naming conventions. It is hard to anticipate if it will be good or bad choice . But I see your points. And changing directory, alter .git/config afterwords manually is not a big deal. Probably we can close this now.

**Comment by melezhik** [comment]
And yeah, as maijor part of my Perl6 modules are Sparrowdo ones, my naming convention is "Sparrowdo-*" )))

**Comment by jonathanstowe** [comment]
To be honest I only use some kind of prefix if there is going to be a clash with some existing repository I might have, but hey.

**Comment by gfldex** [comment]
The prefix can now be set in the meta6.cfg with `create.prefix=your-prefix-here-`.

**Comment by melezhik** [comment]
Thanks!
